#!/usr/bin/env python3
import argparse
import csv
import json
import math
import re
import statistics
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate richer diagnostics for rolling multi-window runs "
            "(execution/gate/risk/sizing/timing) from summary CSV + per-window JSONL."
        )
    )
    parser.add_argument(
        "--summary-csv",
        default="logs/multi/btc_roll10.csv",
        help="Input summary CSV generated by scripts/summarize_multi.py.",
    )
    parser.add_argument(
        "--out-prefix",
        default="logs/multi/btc_roll10_diag",
        help="Output prefix for diagnostics artifacts.",
    )
    parser.add_argument(
        "--top-deny-reasons",
        type=int,
        default=8,
        help="Top N deny reasons to render in stacked chart.",
    )
    parser.add_argument(
        "--top-block-reasons",
        type=int,
        default=8,
        help="Top N block reasons to render in stacked chart.",
    )
    parser.add_argument(
        "--skip-plot",
        action="store_true",
        help="Only write CSV/MD artifacts, skip PNG generation.",
    )
    return parser.parse_args()


def parse_int(v, default: int = 0) -> int:
    try:
        if v is None:
            return default
        return int(float(v))
    except Exception:
        return default


def parse_float(v, default: Optional[float] = None) -> Optional[float]:
    try:
        if v is None or v == "":
            return default
        x = float(v)
        if not math.isfinite(x):
            return default
        return x
    except Exception:
        return default


def median_or_none(samples: List[float]) -> Optional[float]:
    if not samples:
        return None
    return float(statistics.median(samples))


def resolve_jsonl(path_value: str) -> Path:
    p = Path(path_value)
    if p.is_absolute():
        return p
    return Path.cwd() / p


def iter_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except Exception:
                continue


def parse_start_ts_from_slug(slug: str) -> Optional[int]:
    if not isinstance(slug, str):
        return None
    m = re.search(r"-(\d{10})$", slug)
    if not m:
        return None
    return int(m.group(1))


def parse_window_metrics(jsonl_path: Path) -> Tuple[Dict[str, object], Counter, Counter]:
    deny_counter: Counter = Counter()
    block_counter: Counter = Counter()
    user_ws_counter: Counter = Counter()

    applied_ts_ms: List[int] = []
    allow_fill_prob_samples: List[float] = []
    slice_qty_samples: List[float] = []
    open_margin_surplus_samples: List[float] = []

    selected_count = 0
    best_action_nonnull_count = 0
    wait_count = 0
    snapshot_count = 0
    can_start_true_count = 0

    max_round_idx = 0
    max_executed_sim_pair_cost: Optional[float] = None
    max_executed_pair_cost_window: Optional[float] = None
    market_slug: Optional[str] = None

    final_spent_total_usdc: Optional[float] = None
    final_total_budget_usdc: Optional[float] = None
    final_pair_cost: Optional[float] = None
    final_qty_up: Optional[float] = None
    final_qty_down: Optional[float] = None

    for obj in iter_jsonl(jsonl_path):
        kind = obj.get("kind")
        data = obj.get("data", {}) or {}

        if kind == "dryrun_candidates":
            if data.get("best_action") is not None:
                best_action_nonnull_count += 1
            if data.get("applied_action") is not None:
                selected_count += 1
            for cand in data.get("candidates", []) or []:
                deny_reason = cand.get("deny_reason")
                if isinstance(deny_reason, str) and deny_reason:
                    deny_counter[deny_reason] += 1
                else:
                    maker_fill_prob = cand.get("maker_fill_prob")
                    if isinstance(maker_fill_prob, (int, float)):
                        allow_fill_prob_samples.append(float(maker_fill_prob))

        elif kind == "dryrun_apply":
            ts_ms = obj.get("ts_ms")
            if isinstance(ts_ms, (int, float)):
                applied_ts_ms.append(int(ts_ms))
            action = data.get("applied_action")
            if isinstance(action, dict):
                sim_pair_cost = action.get("sim_pair_cost")
                if isinstance(sim_pair_cost, (int, float)):
                    val = float(sim_pair_cost)
                    if max_executed_sim_pair_cost is None or val > max_executed_sim_pair_cost:
                        max_executed_sim_pair_cost = val

        elif kind == "user_ws_order":
            raw_type = data.get("raw_type")
            if isinstance(raw_type, str) and raw_type:
                user_ws_counter[raw_type] += 1
                if raw_type == "sim_order_open":
                    open_margin_surplus = data.get("open_margin_surplus")
                    if isinstance(open_margin_surplus, (int, float)):
                        open_margin_surplus_samples.append(float(open_margin_surplus))
                    else:
                        m2a = data.get("hedge_margin_to_opp_ask")
                        req = data.get("hedge_margin_required")
                        if isinstance(m2a, (int, float)) and isinstance(req, (int, float)):
                            open_margin_surplus_samples.append(float(m2a) - float(req))

        elif kind == "live_skip":
            if data.get("reason") == "paper_waiting_open_order":
                wait_count += 1

        elif kind == "dryrun_snapshot":
            snapshot_count += 1
            if data.get("can_start_new_round") is True:
                can_start_true_count += 1

            block_reason = data.get("round_plan_can_start_block_reason")
            if isinstance(block_reason, str) and block_reason:
                block_counter[block_reason] += 1

            slice_qty = data.get("round_plan_slice_qty_current")
            if isinstance(slice_qty, (int, float)):
                slice_qty_samples.append(float(slice_qty))

            ridx = data.get("round_idx")
            if isinstance(ridx, (int, float)):
                max_round_idx = max(max_round_idx, int(ridx))

            if market_slug is None and isinstance(data.get("market_slug"), str):
                market_slug = data.get("market_slug")

            mex = data.get("max_executed_sim_pair_cost_window")
            if isinstance(mex, (int, float)):
                val = float(mex)
                if max_executed_pair_cost_window is None or val > max_executed_pair_cost_window:
                    max_executed_pair_cost_window = val

            spent_total = data.get("spent_total_usdc")
            if isinstance(spent_total, (int, float)):
                final_spent_total_usdc = float(spent_total)
            total_budget = data.get("total_budget_usdc")
            if isinstance(total_budget, (int, float)):
                final_total_budget_usdc = float(total_budget)
            pair_cost = data.get("pair_cost")
            if isinstance(pair_cost, (int, float)):
                final_pair_cost = float(pair_cost)
            qty_up = data.get("qty_up")
            if isinstance(qty_up, (int, float)):
                final_qty_up = float(qty_up)
            qty_down = data.get("qty_down")
            if isinstance(qty_down, (int, float)):
                final_qty_down = float(qty_down)

    apply_count = len(applied_ts_ms)
    open_count = int(user_ws_counter.get("sim_order_open", 0))
    fill_count = int(
        user_ws_counter.get("sim_order_filled_resting", 0)
        + user_ws_counter.get("sim_order_filled", 0)
    )
    requote_count = int(user_ws_counter.get("sim_order_cancel_requote", 0))
    cancel_timeout_count = int(user_ws_counter.get("sim_order_cancel_timeout", 0))
    cancel_unrecoverable_count = int(
        user_ws_counter.get("sim_order_cancel_unrecoverable", 0)
    )
    timeout_extend_count = int(user_ws_counter.get("sim_order_timeout_extend", 0))

    fill_rate = (fill_count / open_count) if open_count > 0 else None
    wait_activity_ratio = (
        wait_count / (wait_count + selected_count)
        if (wait_count + selected_count) > 0
        else None
    )

    apply_interval_p50_secs: Optional[float] = None
    if len(applied_ts_ms) >= 2:
        applied_ts_ms.sort()
        deltas = [
            (applied_ts_ms[i] - applied_ts_ms[i - 1]) / 1000.0
            for i in range(1, len(applied_ts_ms))
        ]
        apply_interval_p50_secs = median_or_none(deltas)

    first_60s_apply_ratio: Optional[float] = None
    start_ts = parse_start_ts_from_slug(market_slug or "")
    if start_ts is not None and apply_count > 0:
        cutoff_ms = start_ts * 1000 + 60_000
        first_60 = sum(1 for ts in applied_ts_ms if ts < cutoff_ms)
        first_60s_apply_ratio = first_60 / apply_count

    can_start_new_round_true_ratio = (
        (can_start_true_count / snapshot_count) if snapshot_count > 0 else None
    )

    total_candidate_denies = sum(deny_counter.values())
    no_quote_denies = int(deny_counter.get("no_quote", 0))
    low_fill_denies = int(deny_counter.get("low_maker_fill_prob", 0))
    no_quote_ratio = (
        (no_quote_denies / total_candidate_denies)
        if total_candidate_denies > 0
        else None
    )
    low_fill_ratio = (
        (low_fill_denies / total_candidate_denies)
        if total_candidate_denies > 0
        else None
    )

    spent_ratio = (
        (final_spent_total_usdc / final_total_budget_usdc)
        if (
            final_spent_total_usdc is not None
            and final_total_budget_usdc is not None
            and final_total_budget_usdc > 0
        )
        else None
    )
    final_abs_net = (
        abs(final_qty_up - final_qty_down)
        if final_qty_up is not None and final_qty_down is not None
        else None
    )

    max_executed_pair = max_executed_sim_pair_cost
    if max_executed_pair is None:
        max_executed_pair = max_executed_pair_cost_window
    elif max_executed_pair_cost_window is not None:
        max_executed_pair = max(max_executed_pair, max_executed_pair_cost_window)

    out = {
        "apply_count": apply_count,
        "selected_count": selected_count,
        "best_action_nonnull_count": best_action_nonnull_count,
        "open_count": open_count,
        "fill_count": fill_count,
        "fill_rate": fill_rate,
        "requote_count": requote_count,
        "cancel_timeout_count": cancel_timeout_count,
        "cancel_unrecoverable_count": cancel_unrecoverable_count,
        "timeout_extend_count": timeout_extend_count,
        "wait_count": wait_count,
        "wait_activity_ratio": wait_activity_ratio,
        "total_candidate_denies": total_candidate_denies,
        "no_quote_denies": no_quote_denies,
        "no_quote_ratio": no_quote_ratio,
        "low_fill_denies": low_fill_denies,
        "low_fill_ratio": low_fill_ratio,
        "allow_fill_prob_p50": median_or_none(allow_fill_prob_samples),
        "open_margin_surplus_p50": median_or_none(open_margin_surplus_samples),
        "median_slice_qty": median_or_none(slice_qty_samples),
        "apply_interval_p50_secs": apply_interval_p50_secs,
        "first_60s_apply_ratio": first_60s_apply_ratio,
        "can_start_new_round_true_ratio": can_start_new_round_true_ratio,
        "max_round_idx": max_round_idx,
        "final_spent_total_usdc": final_spent_total_usdc,
        "final_total_budget_usdc": final_total_budget_usdc,
        "spent_ratio": spent_ratio,
        "final_pair_cost": final_pair_cost,
        "max_executed_sim_pair_cost": max_executed_pair,
        "final_qty_up": final_qty_up,
        "final_qty_down": final_qty_down,
        "final_abs_net": final_abs_net,
        "top_deny_reason": deny_counter.most_common(1)[0][0] if deny_counter else "",
        "top_block_reason": block_counter.most_common(1)[0][0] if block_counter else "",
    }
    return out, deny_counter, block_counter


def write_window_metrics_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    fieldnames = [
        "window_index",
        "window_ts",
        "run_id",
        "jsonl_path",
        "window_pnl_usdc",
        "total_cum_pnl_usdc",
        "apply_count",
        "selected_count",
        "best_action_nonnull_count",
        "open_count",
        "fill_count",
        "fill_rate",
        "requote_count",
        "cancel_timeout_count",
        "cancel_unrecoverable_count",
        "timeout_extend_count",
        "wait_count",
        "wait_activity_ratio",
        "total_candidate_denies",
        "no_quote_denies",
        "no_quote_ratio",
        "low_fill_denies",
        "low_fill_ratio",
        "allow_fill_prob_p50",
        "open_margin_surplus_p50",
        "median_slice_qty",
        "apply_interval_p50_secs",
        "first_60s_apply_ratio",
        "can_start_new_round_true_ratio",
        "max_round_idx",
        "final_spent_total_usdc",
        "final_total_budget_usdc",
        "spent_ratio",
        "final_pair_cost",
        "max_executed_sim_pair_cost",
        "final_qty_up",
        "final_qty_down",
        "final_abs_net",
        "top_deny_reason",
        "top_block_reason",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def write_counter_long_csv(
    path: Path,
    rows: List[Dict[str, object]],
    counters: Dict[str, Counter],
    name: str,
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["window_index", "window_ts", "run_id", name, "count"]
        )
        writer.writeheader()
        for row in rows:
            run_id = str(row.get("run_id", ""))
            c = counters.get(run_id, Counter())
            for key, count in c.items():
                writer.writerow(
                    {
                        "window_index": row.get("window_index"),
                        "window_ts": row.get("window_ts"),
                        "run_id": run_id,
                        name: key,
                        "count": count,
                    }
                )


def maybe_plot(
    rows: List[Dict[str, object]],
    deny_counters: Dict[str, Counter],
    block_counters: Dict[str, Counter],
    out_prefix: Path,
    top_deny_reasons: int,
    top_block_reasons: int,
) -> List[Path]:
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except Exception:
        return []

    if not rows:
        return []

    palette = ["#2563eb", "#16a34a", "#dc2626", "#9333ea", "#ea580c", "#0891b2"]
    x = list(range(len(rows)))
    x_labels = [str(r.get("window_ts", "")) for r in rows]
    generated: List[Path] = []

    def arr(key: str, default: float = 0.0) -> List[float]:
        out: List[float] = []
        for r in rows:
            v = parse_float(r.get(key), None)
            out.append(v if v is not None else default)
        return out

    def arr_opt(key: str) -> List[Optional[float]]:
        return [parse_float(r.get(key), None) for r in rows]

    # 1) overview figure
    fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=True)
    ax = axes[0, 0]
    ax.bar(x, arr("window_pnl_usdc", 0.0), color=palette[0], alpha=0.35, label="window_pnl_usdc")
    ax.plot(x, arr("total_cum_pnl_usdc", 0.0), color=palette[2], marker="o", label="total_cum_pnl_usdc")
    ax.axhline(0.0, color="gray", linestyle="--", linewidth=1)
    ax.set_title("PnL by Window")
    ax.grid(alpha=0.2)
    ax.legend()

    ax = axes[0, 1]
    ax.plot(x, arr("final_spent_total_usdc", 0.0), color=palette[1], marker="o", label="spent_total_usdc")
    ax.plot(x, arr("final_total_budget_usdc", 0.0), color=palette[3], marker="o", label="total_budget_usdc")
    ax2 = ax.twinx()
    ax2.plot(x, arr_opt("spent_ratio"), color=palette[4], marker="x", label="spent_ratio")
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, loc="best")
    ax.set_title("Capital Usage")
    ax.grid(alpha=0.2)

    ax = axes[1, 0]
    ax.plot(x, arr_opt("final_pair_cost"), color=palette[0], marker="o", label="final_pair_cost")
    ax.plot(
        x,
        arr_opt("max_executed_sim_pair_cost"),
        color=palette[2],
        marker="x",
        label="max_executed_sim_pair_cost",
    )
    ax.axhline(0.995, color="tab:red", linestyle="--", linewidth=1, label="hard_cap=0.995")
    ax.axhline(1.0, color="gray", linestyle=":", linewidth=1, label="1.0")
    ax.set_title("Pair Cost Safety")
    ax.grid(alpha=0.2)
    ax.legend()

    ax = axes[1, 1]
    ax.plot(x, arr("open_count", 0.0), color=palette[3], marker="o", label="open_count")
    ax.plot(x, arr("fill_count", 0.0), color=palette[1], marker="o", label="fill_count")
    ax2 = ax.twinx()
    ax2.plot(x, arr_opt("fill_rate"), color=palette[5], marker="x", label="fill_rate")
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, loc="best")
    ax.set_title("Open/Fill and Fill Rate")
    ax.grid(alpha=0.2)

    for a in axes.flatten():
        a.set_xticks(x)
        a.set_xticklabels(x_labels, rotation=45, ha="right")

    fig.tight_layout()
    p1 = out_prefix.parent / f"{out_prefix.name}_overview.png"
    fig.savefig(p1, dpi=140)
    plt.close(fig)
    generated.append(p1)

    # 2) timing/sizing figure
    fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=True)
    ax = axes[0, 0]
    ax.plot(x, arr_opt("apply_interval_p50_secs"), color=palette[0], marker="o", label="apply_interval_p50_secs")
    ax.axhline(0.3, color="tab:green", linestyle="--", linewidth=1, label="0.3s")
    ax.axhline(0.8, color="tab:orange", linestyle="--", linewidth=1, label="0.8s")
    ax2 = ax.twinx()
    ax2.plot(x, arr_opt("first_60s_apply_ratio"), color=palette[2], marker="x", label="first_60s_apply_ratio")
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, loc="best")
    ax.set_title("Execution Timing")
    ax.grid(alpha=0.2)

    ax = axes[0, 1]
    ax.plot(x, arr_opt("median_slice_qty"), color=palette[3], marker="o", label="median_slice_qty")
    ax.axhline(8.0, color="tab:red", linestyle="--", linewidth=1, label="slice_qty_limit=8")
    ax.legend()
    ax.set_title("Sizing")
    ax.grid(alpha=0.2)

    ax = axes[1, 0]
    ax.plot(x, arr_opt("allow_fill_prob_p50"), color=palette[1], marker="o", label="allow_fill_prob_p50")
    ax.axhline(0.07, color="tab:green", linestyle="--", linewidth=1, label="min=0.07")
    ax2 = ax.twinx()
    ax2.plot(x, arr_opt("low_fill_ratio"), color=palette[2], marker="x", label="low_fill_ratio")
    ax2.plot(x, arr_opt("no_quote_ratio"), color=palette[5], marker="x", label="no_quote_ratio")
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, loc="best")
    ax.set_title("Fillability and Deny Ratios")
    ax.grid(alpha=0.2)

    ax = axes[1, 1]
    ax.plot(x, arr_opt("wait_activity_ratio"), color=palette[0], marker="o", label="wait_activity_ratio")
    ax.axhline(0.65, color="tab:red", linestyle="--", linewidth=1, label="max=0.65")
    ax2 = ax.twinx()
    ax2.plot(
        x,
        arr_opt("can_start_new_round_true_ratio"),
        color=palette[1],
        marker="x",
        label="can_start_new_round_true_ratio",
    )
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, loc="best")
    ax.set_title("State and Opportunity Activity")
    ax.grid(alpha=0.2)

    for a in axes.flatten():
        a.set_xticks(x)
        a.set_xticklabels(x_labels, rotation=45, ha="right")

    fig.tight_layout()
    p2 = out_prefix.parent / f"{out_prefix.name}_timing_sizing.png"
    fig.savefig(p2, dpi=140)
    plt.close(fig)
    generated.append(p2)

    total_deny = Counter()
    total_block = Counter()
    for row in rows:
        rid = str(row.get("run_id", ""))
        total_deny.update(deny_counters.get(rid, Counter()))
        total_block.update(block_counters.get(rid, Counter()))
    top_denies = [k for k, _ in total_deny.most_common(top_deny_reasons)]
    top_blocks = [k for k, _ in total_block.most_common(top_block_reasons)]

    # 3) events + stacked deny/block
    fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=True)
    ax = axes[0, 0]
    ax.bar([i - 0.2 for i in x], arr("open_count", 0.0), width=0.2, label="open")
    ax.bar(x, arr("fill_count", 0.0), width=0.2, label="fill")
    ax.bar([i + 0.2 for i in x], arr("apply_count", 0.0), width=0.2, label="apply")
    ax.set_title("Core Execution Counts")
    ax.grid(alpha=0.2)
    ax.legend()

    ax = axes[0, 1]
    ax.bar([i - 0.3 for i in x], arr("requote_count", 0.0), width=0.2, label="cancel_requote")
    ax.bar([i - 0.1 for i in x], arr("cancel_timeout_count", 0.0), width=0.2, label="cancel_timeout")
    ax.bar([i + 0.1 for i in x], arr("cancel_unrecoverable_count", 0.0), width=0.2, label="cancel_unrecoverable")
    ax.bar([i + 0.3 for i in x], arr("timeout_extend_count", 0.0), width=0.2, label="timeout_extend")
    ax.set_title("Cancel/Repair Events")
    ax.grid(alpha=0.2)
    ax.legend()

    ax = axes[1, 0]
    deny_bottom = [0.0] * len(rows)
    for idx, reason in enumerate(top_denies):
        vals = [
            float(deny_counters.get(str(r.get("run_id", "")), Counter()).get(reason, 0))
            for r in rows
        ]
        ax.bar(x, vals, bottom=deny_bottom, label=reason, color=palette[idx % len(palette)])
        deny_bottom = [deny_bottom[i] + vals[i] for i in range(len(vals))]
    ax.set_title("Top Deny Reasons (stacked count)")
    ax.grid(alpha=0.2)
    if top_denies:
        ax.legend(fontsize=8)

    ax = axes[1, 1]
    block_bottom = [0.0] * len(rows)
    for idx, reason in enumerate(top_blocks):
        vals = [
            float(block_counters.get(str(r.get("run_id", "")), Counter()).get(reason, 0))
            for r in rows
        ]
        ax.bar(x, vals, bottom=block_bottom, label=reason, color=palette[idx % len(palette)])
        block_bottom = [block_bottom[i] + vals[i] for i in range(len(vals))]
    ax.set_title("Top can_start Block Reasons (stacked count)")
    ax.grid(alpha=0.2)
    if top_blocks:
        ax.legend(fontsize=8)

    for a in axes.flatten():
        a.set_xticks(x)
        a.set_xticklabels(x_labels, rotation=45, ha="right")

    fig.tight_layout()
    p3 = out_prefix.parent / f"{out_prefix.name}_events_gates.png"
    fig.savefig(p3, dpi=140)
    plt.close(fig)
    generated.append(p3)

    return generated


def write_markdown(
    path: Path,
    rows: List[Dict[str, object]],
    deny_counters: Dict[str, Counter],
    block_counters: Dict[str, Counter],
    generated_plots: List[Path],
    metrics_csv: Path,
    deny_csv: Path,
    block_csv: Path,
) -> None:
    total_pnl = sum(parse_float(r.get("window_pnl_usdc"), 0.0) or 0.0 for r in rows)
    med_fill_rate = median_or_none(
        [parse_float(r.get("fill_rate"), None) for r in rows if parse_float(r.get("fill_rate"), None) is not None]
    )
    med_spent_ratio = median_or_none(
        [
            parse_float(r.get("spent_ratio"), None)
            for r in rows
            if parse_float(r.get("spent_ratio"), None) is not None
        ]
    )
    med_pair_cost = median_or_none(
        [
            parse_float(r.get("final_pair_cost"), None)
            for r in rows
            if parse_float(r.get("final_pair_cost"), None) is not None
        ]
    )

    deny_total = Counter()
    block_total = Counter()
    for r in rows:
        rid = str(r.get("run_id", ""))
        deny_total.update(deny_counters.get(rid, Counter()))
        block_total.update(block_counters.get(rid, Counter()))

    lines: List[str] = []
    lines.append("# Roll Diagnostics")
    lines.append("")
    lines.append(f"- Windows: {len(rows)}")
    lines.append(f"- Total PnL (USDC): {total_pnl:.6f}")
    lines.append(
        f"- Median fill_rate: {med_fill_rate:.4f}" if med_fill_rate is not None else "- Median fill_rate: n/a"
    )
    lines.append(
        f"- Median spent_ratio: {med_spent_ratio:.4f}" if med_spent_ratio is not None else "- Median spent_ratio: n/a"
    )
    lines.append(
        f"- Median final_pair_cost: {med_pair_cost:.6f}" if med_pair_cost is not None else "- Median final_pair_cost: n/a"
    )
    lines.append("")
    lines.append("## Artifacts")
    lines.append(f"- metrics csv: `{metrics_csv}`")
    lines.append(f"- deny reasons csv: `{deny_csv}`")
    lines.append(f"- block reasons csv: `{block_csv}`")
    for p in generated_plots:
        lines.append(f"- plot: `{p}`")
    lines.append("")
    lines.append("## Top Deny Reasons")
    lines.append("")
    for key, cnt in deny_total.most_common(10):
        lines.append(f"- `{key}`: {cnt}")
    lines.append("")
    lines.append("## Top can_start Block Reasons")
    lines.append("")
    for key, cnt in block_total.most_common(10):
        lines.append(f"- `{key}`: {cnt}")
    lines.append("")
    lines.append("## Per-Window Quick View")
    lines.append("")
    lines.append(
        "| idx | window_ts | pnl | spent_ratio | pair_cost | fill_rate | apply_interval_p50_s | median_slice_qty | top_deny | top_block |"
    )
    lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---|---|")
    for r in rows:
        lines.append(
            "| {window_index} | {window_ts} | {window_pnl_usdc} | {spent_ratio} | {final_pair_cost} | {fill_rate} | {apply_interval_p50_secs} | {median_slice_qty} | {top_deny_reason} | {top_block_reason} |".format(
                **r
            )
        )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    summary_csv = Path(args.summary_csv)
    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    if not summary_csv.exists():
        print(f"summary csv not found: {summary_csv}")
        return 1

    rows_raw: List[Dict[str, object]] = []
    with summary_csv.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows_raw.append(row)

    rows_raw.sort(key=lambda r: parse_int(r.get("window_ts"), 0))
    rows: List[Dict[str, object]] = []
    deny_counters: Dict[str, Counter] = {}
    block_counters: Dict[str, Counter] = {}

    for idx, row in enumerate(rows_raw, 1):
        run_id = str(row.get("run_id", "")).strip()
        jsonl_path = resolve_jsonl(str(row.get("jsonl_path", "")).strip())
        if not jsonl_path.exists():
            continue

        parsed, deny_c, block_c = parse_window_metrics(jsonl_path)
        deny_counters[run_id] = deny_c
        block_counters[run_id] = block_c

        merged = dict(parsed)
        merged["window_index"] = idx
        merged["window_ts"] = parse_int(row.get("window_ts"), 0)
        merged["run_id"] = run_id
        merged["jsonl_path"] = str(jsonl_path)
        merged["window_pnl_usdc"] = parse_float(row.get("window_pnl_usdc"), None)
        merged["total_cum_pnl_usdc"] = parse_float(row.get("total_cum_pnl_usdc"), None)

        # Prefer parsed final fields; fallback to summary csv when missing.
        if merged.get("final_spent_total_usdc") is None:
            merged["final_spent_total_usdc"] = parse_float(row.get("spent_total_usdc"), None)
        if merged.get("final_pair_cost") is None:
            merged["final_pair_cost"] = parse_float(row.get("final_pair_cost"), None)
        if merged.get("final_qty_up") is None:
            merged["final_qty_up"] = parse_float(row.get("final_qty_up"), None)
        if merged.get("final_qty_down") is None:
            merged["final_qty_down"] = parse_float(row.get("final_qty_down"), None)
        if merged.get("final_abs_net") is None:
            q_up = parse_float(merged.get("final_qty_up"), None)
            q_dn = parse_float(merged.get("final_qty_down"), None)
            merged["final_abs_net"] = abs(q_up - q_dn) if q_up is not None and q_dn is not None else None

        rows.append(merged)

    metrics_csv = out_prefix.parent / f"{out_prefix.name}_window_metrics.csv"
    deny_csv = out_prefix.parent / f"{out_prefix.name}_deny_reasons.csv"
    block_csv = out_prefix.parent / f"{out_prefix.name}_block_reasons.csv"
    md_path = out_prefix.parent / f"{out_prefix.name}.md"

    write_window_metrics_csv(metrics_csv, rows)
    write_counter_long_csv(deny_csv, rows, deny_counters, "deny_reason")
    write_counter_long_csv(block_csv, rows, block_counters, "block_reason")

    generated_plots: List[Path] = []
    if not args.skip_plot:
        generated_plots = maybe_plot(
            rows,
            deny_counters,
            block_counters,
            out_prefix,
            top_deny_reasons=max(1, args.top_deny_reasons),
            top_block_reasons=max(1, args.top_block_reasons),
        )

    write_markdown(
        md_path,
        rows,
        deny_counters,
        block_counters,
        generated_plots,
        metrics_csv,
        deny_csv,
        block_csv,
    )

    print(f"wrote {metrics_csv}")
    print(f"wrote {deny_csv}")
    print(f"wrote {block_csv}")
    print(f"wrote {md_path}")
    for p in generated_plots:
        print(f"wrote {p}")
    if not generated_plots and not args.skip_plot:
        print("INFO: plots not generated (no data)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
